# Controller manager config
controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    # Controller Node
    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    # State Publisher Node
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Controller Config
diff_drive_base_controller:
  ros__parameters:

    # List of joints (MUST MATCH JOINT NAME IN URDF FILE)
    left_wheel_names:  ["front_left_wheel", "rear_left_wheel"]
    right_wheel_names: ["front_right_wheel", "rear_right_wheel"]

    wheel_seperation: 1.0
    wheels_per_side: 2 #Actually 2 but they share control
    wheel_radius: 0.33

    wheel_seperation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0

    # Odometry
    odom_frame_id: odom
    enable_odom_tf: false # Has .nan values in odom transform

    # Base link
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    use_stamped_vel: false
    # velocity_rolling_window_size: 10

    # Publish limited velocity
    publish_cmd: true
    
    # Publish wheel data
    publish_wheel_data: true
    
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0